name: Generate Packages Index
on:
  push:
    branches: [ master ]
    paths:
      - 'debs/**'  # 只要 debs 文件夹有变化，就自动执行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dpkg
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev zstd

      - name: Generate Packages
        run: |
          dpkg-scanpackages debs/ /dev/null > Packages
          zstd -f -c Packages > Packages.zst

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Packages Packages.zst
          git commit -m "Auto-update Packages index" || echo "No changes to commit"
          git push
